---
config:
  theme: redux-color
  look: neo
  fontFamily: '''Source Code Pro Variable'', monospace'
  themeVariables:
    fontFamily: '''Source Code Pro Variable'', monospace'
---
sequenceDiagram
  %% LEGEND
  %% Dsp: Dispatcher
  %% Prc: Processor
  %% Fac: Factory
  %% Str: Strategy
  %% Bou: Boundry
  %% Act: Actor

  actor ActUsr as User
  participant BouCli as CLI<br>[Presentation]<br>[main.py]
  participant CmdRun as cli.py<br>[Command]<br>[main.py]
  participant FacSlc as Selector<br>[Factory]
  participant DspOrc as Orchestrator<br>[Dispatcher]
  participant DBSrc as Source<br>Database
  participant APISrc as Source<br>API Endpoint
  participant DBPip  as Pipeline<br>Database
  participant PrcFet as Fetcher<br>[Processor]
  participant PrcDcd as Decoder<br>[Processor]
  participant PrcExr as Extractor<br>[Processor]
  participant PrcTrs as Transformer<br>[Processor]
  participant PrcLod as Loader<br>[Processor]
  participant DBTrg as Target<br>Database

  autonumber


  %%SEQUENCE
  ActUsr ->> BouCli: enters prompt: run kwargs
  activate BouCli
  BouCli ->> CmdRun: passes prompt kwargs
  deactivate BouCli
  activate CmdRun
  CmdRun -->>CmdRun: input_args = InputArgs(**kwargs)
  Note over CmdRun: recourse for<br/>validation to:<br/>[PydanticModel]<br/>(InputArgs)
  CmdRun ->> DspOrc: Orchestrator(input_args, **store_kwargs)
  Note over CmdRun: **store_kwargs<br>these are hardcoded<br>inner SQLite stores<br>TODO: parametarize
  deactivate CmdRun
  activate DspOrc
    DspOrc ->> FacSlc: selector.<br/>build_pipeline_route<br/>(**input_args)
    activate FacSlc
    Note over FacSlc: recourse to:<br/>[Strategy Map]
    FacSlc->>FacSlc: ._infer_strategy<br/>(**input_args)
    FacSlc-->>DspOrc: returns <br/>route_args
    deactivate FacSlc
    DspOrc->>PrcFet: .fetch<br/>(**route_args)
    activate PrcFet
    Note over PrcFet: recourse to:<br/> [Fetch Strategy]
    PrcFet->>PrcFet: .context<br/>.fetch<br/>(**route_args)
    alt Source: Database
    Note over PrcFet: recourse to:<br/> [ORM for Source DB]
    PrcFet->>DBSrc: queries db
    activate DBSrc
    DBSrc-->> PrcFet: returns fetched data
    deactivate DBSrc
    else Source: API Endpoint
    PrcFet->>APISrc: .send_request<br/>(**route_args)
    activate APISrc
    APISrc-->> PrcFet: returns fetched data
    deactivate APISrc
    end
    Note over PrcFet: recourse to: <br/> [Fetched DTO]
    PrcFet->>PrcFet: ._enrich_registry_record()<br/>(add content hash)
    Note over PrcFet: recourse to:<br/> [Fetch ORM for Pipe DB]
    activate DBPip
    PrcFet->>DBPip: writes to DB
    Note over PrcFet: recourse to<br/> [Registry DTO]
    PrcFet->>PrcFet: ._populate_registry_meta()
    Note over PrcFet: recourse to:<br/> [Reg ORM for Pipe DB]
    PrcFet ->> DBPip: writes to DB
    deactivate DBPip
    PrcFet -->> DspOrc: returns
    deactivate PrcFet
    deactivate DspOrc