---
config:
  theme: redux-color
  look: classic
  fontFamily: '''Source Code Pro Variable'', monospace'
  themeVariables:
    fontFamily: '''Source Code Pro Variable'', monospace'
---
sequenceDiagram
  %% LEGEND
  %% Dsp: Dispatcher
  %% Prc: Processor
  %% Fac: Factory
  %% Str: Strategy
  %% Bou: Boundry
  %% Act: Actor

  actor ActUsr as User
  participant BouCli as CLI
  participant DspCmd as CommandManager<br/>[Dispatcher]
  participant FacSlc as Selector<br/>[Factory]
  participant DspOrc as Orchestrator<br/>[Dispatcher]
  participant DBSrc as Source<br/>Database
  participant APISrc as Source<br/>API Endpoint
  participant DBPip as Pipeline<br/>Database
  participant PrcFet as Fetcher<br/>[Processor]
  participant PrcDcd as Decoder<br/>[Processor]
  participant PrcExr as Extractor<br/>[Processor]
  participant PrcTrs as Transformer<br/>[Processor]
  participant PrcLod as Loader<br/>[Processor]
  participant DBTrg as Target

  autonumber


  %%SEQUENCE
  ActUsr ->> BouCli: enters prompt
  activate BouCli
  BouCli ->> DspCmd: passes prompt
  deactivate BouCli
  activate DspCmd
  DspCmd ->> DspCmd: checks prompt
  alt INVALID PROMPT
    Note over DspCmd: Error
    DspCmd -->> DspCmd: logs and raises error
  else VALID PROMPT
    DspCmd ->> DspOrc: orchestrate<br/>.run(**runtime_args)
  end
  deactivate DspCmd
  activate DspOrc
    DspOrc ->> FacSlc: selector.<br/>build_pipeline_route<br/>(**runtime_args)
    activate FacSlc
    Note over FacSlc: recourse to:<br/>[Strategy Map]
    FacSlc->>FacSlc: _infer_source<br/>_infer_target<br/>_infer_strategy<br/>based on(**runtime_args)
    FacSlc-->>DspOrc: returns <br/>pipeline route args<br/>(**route_args)
    deactivate FacSlc
    DspOrc->>PrcFet: .fetch<br/>(**route_args)
    activate PrcFet
    Note over PrcFet: recourse to:<br/> [Fetch Strategy]
    PrcFet->>PrcFet: .context<br/>.fetch<br/>(**route_args, Strategy())
    alt Source: Database
    Note over PrcFet: recourse to:<br/> [ORM for Source DB]
    PrcFet->>DBSrc: queries db
    activate DBSrc
    DBSrc-->> PrcFet: returns fetched data
    deactivate DBSrc
    else Source: API Endpoint
    PrcFet->>APISrc: .send_request<br/>(**route_args)
    activate APISrc
    APISrc-->> PrcFet: returns fetched data
    deactivate APISrc
    end
    Note over PrcFet: recourse to: <br/> [Fetched DTO]
    PrcFet->>PrcFet: ._enrich_registry_record()<br/>(add content hash)
    Note over PrcFet: recourse to:<br/> [Fetch ORM for Pipe DB]
    activate DBPip
    PrcFet->>DBPip: writes to DB
    Note over PrcFet: recourse to<br/> [Registry DTO]
    PrcFet->>PrcFet: ._populate_registry_meta()
    Note over PrcFet: recourse to:<br/> [Reg ORM for Pipe DB]
    PrcFet ->> DBPip: writes to DB
    deactivate DBPip
    deactivate PrcFet
    deactivate DspOrc